apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: becore
    meta.helm.sh/release-namespace: backend
  creationTimestamp: "2023-05-29T14:22:06Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: becore
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: becore
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: becore-0.1.0
  name: becore
  namespace: backend
  resourceVersion: "25913"
  uid: 6a5fa691-21ed-47d9-ad82-93fb3c858fe2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: becore
      app.kubernetes.io/name: becore
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: becore
        app.kubernetes.io/name: becore
    spec:
      containers:
      - image: fajarsujai/be-core:5dcb2af
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: becore
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: becore
      serviceAccountName: becore
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-05-29T14:22:17Z"
    lastUpdateTime: "2023-05-29T14:22:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-05-29T14:22:06Z"
    lastUpdateTime: "2023-05-29T14:22:17Z"
    message: ReplicaSet "becore-644489f469" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
