apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: becore
    meta.helm.sh/release-namespace: backend
  creationTimestamp: "2023-05-29T15:41:06Z"
  labels:
    app.kubernetes.io/instance: becore
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: becore
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: becore-0.1.0
  name: becore
  namespace: backend
  resourceVersion: "28789"
  uid: b05ca2cc-aece-45e9-beb7-1ffb30fb1b01
spec:
  clusterIP: 10.101.230.16
  clusterIPs:
  - 10.101.230.16
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: becore
    app.kubernetes.io/name: becore
  sessionAffinity: None
  type: ClusterIP
