apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: becore
      meta.helm.sh/release-namespace: backend
    creationTimestamp: "2023-05-29T15:41:06Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: becore
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: becore
      app.kubernetes.io/version: 1.16.0
      helm.sh/chart: becore-0.1.0
    name: becore
    namespace: backend
    resourceVersion: "30871"
    uid: ea2f6e79-694d-47b1-aaaf-5af7e44e6ffd
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: becore
        app.kubernetes.io/name: becore
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: becore
          app.kubernetes.io/name: becore
      spec:
        containers:
        - image: fajarsujai/be-core:5dcb2af
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: becore
          ports:
          - containerPort: 3000
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: becore
        serviceAccountName: becore
        terminationGracePeriodSeconds: 30
